# Generated by Django 5.1.6 on 2025-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('years_of_driving_experience', models.IntegerField()),
                ('owns_car', models.BooleanField()),
                ('current_car', models.CharField(max_length=100)),
                ('annual_miles', models.IntegerField()),
                ('owned_before', models.BooleanField()),
                ('previous_cars', models.TextField()),
                ('primary_purpose', models.CharField(max_length=100)),
                ('preferred_car_type', models.CharField(max_length=100)),
                ('preferred_car_brand', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seating_capacity', models.IntegerField()),
                ('cargo_space', models.CharField(max_length=100)),
                ('preferred_fuel_type', models.CharField(max_length=100)),
                ('eco_friendly', models.BooleanField()),
                ('transmission_type', models.CharField(max_length=100)),
                ('desired_fuel_efficiency', models.CharField(max_length=100)),
                ('preferred_drive_type', models.CharField(max_length=100)),
                ('advanced_technology', models.BooleanField()),
                ('must_have_features', models.TextField()),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
