# Generated by Django 5.1.6 on 2025-03-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='Toyota', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_economy_city', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fuel_economy_highway', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('interior_features', models.TextField(blank=True, null=True)),
                ('safety_features', models.TextField(blank=True, null=True)),
                ('technology_features', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
