# Generated by Django 5.1.6 on 2025-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_body_type_car_drivetrain_car_fuel_type_car_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image_url',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
